# Generated by Django 5.2.14 on 2026-05-28 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=20)),
                ('status', models.CharField(choices=[('RAW', 'Raw'), ('PENDING_REVIEW', 'Pending Review'), ('SUSPICIOUS', 'Suspicious'), ('VALIDATION_FAILED', 'Validation Failed'), ('APPROVED_LOCKED', 'Approved Locked')], default='RAW', max_length=32)),
                ('file_name', models.CharField(max_length=500)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_batches', to='emissions_tracker.organization')),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=255)),
                ('action_taken', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes_json', models.JSONField(blank=True, default=dict)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emissions_audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_trails', to='emissions_tracker.organization')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RawDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('RAW', 'Raw'), ('PENDING_REVIEW', 'Pending Review'), ('SUSPICIOUS', 'Suspicious'), ('VALIDATION_FAILED', 'Validation Failed'), ('APPROVED_LOCKED', 'Approved Locked')], default='RAW', max_length=32)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_data_records', to='emissions_tracker.ingestionbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_data_records', to='emissions_tracker.organization')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_category', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20)),
                ('activity_type', models.CharField(max_length=255)),
                ('raw_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('emissions_factor', models.DecimalField(decimal_places=10, max_digits=20)),
                ('calculated_co2e_kg', models.DecimalField(decimal_places=6, max_digits=20)),
                ('billing_start_date', models.DateField()),
                ('billing_end_date', models.DateField()),
                ('verification_status', models.CharField(choices=[('RAW', 'Raw'), ('PENDING_REVIEW', 'Pending Review'), ('SUSPICIOUS', 'Suspicious'), ('VALIDATION_FAILED', 'Validation Failed'), ('APPROVED_LOCKED', 'Approved Locked')], default='PENDING_REVIEW', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_emissions_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_emission_records', to='emissions_tracker.organization')),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_emission_records', to='emissions_tracker.rawdatarecord')),
            ],
            options={
                'ordering': ['-billing_end_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['organization', 'ingested_at'], name='emissions_t_organiz_0e83d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['organization', 'status'], name='emissions_t_organiz_467bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['organization', 'timestamp'], name='emissions_t_organiz_979f39_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['organization', 'record_id'], name='emissions_t_organiz_d1da1e_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdatarecord',
            index=models.Index(fields=['organization', 'status'], name='emissions_t_organiz_84551d_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdatarecord',
            index=models.Index(fields=['batch', 'organization'], name='emissions_t_batch_i_667a17_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['organization', 'verification_status'], name='emissions_t_organiz_9d21c7_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['organization', 'scope_category'], name='emissions_t_organiz_f2f77c_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['raw_record', 'organization'], name='emissions_t_raw_rec_b8ef3c_idx'),
        ),
    ]
